# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RunnerBe-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RunnerBe-iOS

  # RIBS
  pod 'RIBs', '~> 0.9.1'

  # SwiftGen
  pod 'SwiftGen', '~> 6.0'
  # SwiftFormat
  pod 'SwiftFormat/CLI'
  # Moya with rx
  pod 'Moya/RxSwift', '~> 13.0'
  # RxSwift & Cocoa
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  # SnapKit
  pod 'SnapKit', '~> 5.0.0'
  # Then
  pod 'Then'

end
