# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RunnerBe-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RunnerBe-iOS

  # Needle
  pod 'NeedleFoundation'
  
  # SwiftGen
  pod 'SwiftGen', '~> 6.0'
  # SwiftFormat
  pod 'SwiftFormat/CLI'
  # Moya with rx
  pod 'Moya/RxSwift', '~> 15.0'
  # RxSwift & Cocoa
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  # RxGesture
  pod 'RxGesture'
  # SnapKit
  pod 'SnapKit', '~> 5.0.0'
  # Then
  pod 'Then'

  # Kakao Login
  pod 'KakaoSDKCommon' # 필수 모듈
  pod 'KakaoSDKAuth' # 카카오 로그인

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end

end
